title:       Topological Data Analysis and Beyond
description: Workshop at NeurIPS 2020

timezone: Europe/Zurich

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Organisers: "/organisers"
  Programme Committee: "/committee"
  FAQ: "/faq"

markdown: kramdown

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
