title:       Topological Data Analysis and Beyond
description: Workshop at NeurIPS 2020

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Organisers: "/organisers"
  Speakers: "/speakers"
  Schedule: "/schedule"

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
