title:       Topological Data Analysis and Beyond
description: Workshop at NeurIPS 2020

navigation:
  Home: "/"
  Speakers: "/speakers"
  Schedule: "/schedule"

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
